Баранов Виталий
alinkov/maven-practice pull request #1
Opened 2018-12-17 12:01 UTC by vitalib

2018-12-18 11:38 UTC, alinkov requested changes
Необходимо поправить:
1)Параметры задать нельзя
2)NPE в логе, если не директория, а файл
3)Checkstyle plugin тут бы не помешал

2018-12-18 11:38 UTC, alinkov commented on pom.xml
> +    <artifactId>filesCounter-maven-plugin</artifactId>
`filesCounter` - не должно быть такого именования.
files-counter или filecounter

2018-12-18 11:38 UTC, alinkov commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +    class Pair {
необходимо дать нормально имя для класса.
И без него код получше бы получился

2018-12-18 11:38 UTC, alinkov commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +            Pair pair = dirsQueue.poll();
может лучше сделать это рекурсией?

2018-12-18 11:38 UTC, alinkov commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +            } catch (NullPointerException e) {
лучше так не делать

2018-12-18 15:02 UTC, vitalib commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +            } catch (NullPointerException e) {
Разобрался, NPE выбрасывалось, когда не было прав на чтение файлов и директорий, сделал проверку, теперь норм.

2018-12-18 15:02 UTC, vitalib commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +            Pair pair = dirsQueue.poll();
Да, с рекрусией красивее, переделал

2018-12-18 15:02 UTC, vitalib commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +    class Pair {
Убрал

2018-12-18 15:02 UTC, vitalib commented on pom.xml
> +    <artifactId>filesCounter-maven-plugin</artifactId>
Поправил

2018-12-18 15:05 UTC, vitalib commented on pom.xml
> +    <artifactId>filesCounter-maven-plugin</artifactId>
Добавил возможность запуска из CLI
mvn -Ddir="/home/vitalib/projects" -Ddepth=5 -Dfiles=10 ru.vitalib:filecounter-maven-plugin:countFiles

2018-12-18 15:12 UTC, vitalib commented
Вроде все поправил.

2018-12-19 09:05 UTC, alinkov requested changes
Плагин стал намного лучше.
Но еще стоит внести небольшие правки

2018-12-19 09:05 UTC, alinkov commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +    @Parameter(defaultValue = "${basedir}", property = "dir")
зачем параметры называть по-другому?
`@Parameter(defaultValue = "${basedir}", property = "rootDirectory")`

2018-12-19 09:05 UTC, alinkov commented on src/main/java/ru/vitalib/testplugin/CountFilesMojo.java
> +        if (!rootDirectory.exists()) {
Вот тут как раз не помешали бы проверки
`rootDirectory.canRead()`
и правильно добавить проверку 
`rootDirectory.isDirectory()`

2018-12-19 11:40 UTC, vitalib commented
Поправил

2018-12-20 05:45 UTC, alinkov approved these changes

2018-12-20 05:46 UTC, alinkov commented
Засчитано

2018-12-20 05:46 UTC, closed without merging