ДЗ maven Филиппов
alinkov/maven-practice pull request #10
Opened 2018-12-26 05:27 UTC by Afftobus

Сделал простой плагин, рекурсивно сканящий заданную директорию и считающий количество файлов и общий размер таковых. 

Использовал тест для того, чтобы дёргать его функционал. 

У плагина 3 параметра, help создаётся автоматически.

2018-12-26 12:33 UTC, k-vasiliev commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +            for(File item : start.listFiles()){
Упадет если не хватит прав на чтение

2018-12-26 12:35 UTC, k-vasiliev commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +                else{
Я бы рекомендовал посмотреть code-style, у тебя немного отличается от общепринятого. Если используешь IDEA, то у нее есть автоформат по ctr+alt+L

2018-12-26 16:03 UTC, alinkov requested changes
Добавь module в основной проект
И рекомендую добавить checkstyle plugin

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/pom.xml
> +  <!-- FIXME change it to the project's website -->
change it

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/pom.xml
> +    <maven.compiler.source>1.7</maven.compiler.source>
поменяй версию.
Не меньше 8 поставь

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/pom.xml
> +          <plugin>
убери то, что не используется

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +public class TestFiles
ох, почему объявление класса аж в 3 строки

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +    private void recursiveDirScan(File start, ArrayList<File> filelist)
Лучше следовать порядку, который рекомендует оракл 
https://www.oracle.com/technetwork/java/codeconventions-141855.html

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +import java.io.FileWriter;
почисть ненужные импорты

2018-12-26 16:03 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +        Long minCount = new Long(Integer.parseInt(minFileCount));
что-то какая-то сложная махинация.
зачем тут вообще Long?

2018-12-27 08:35 UTC, fkhodkov commented on homework-maven-plugin/src/test/java/hh/MyMojoTest.java
> +    public void testSomething()
При работе твоего плагина возможны, как минимум, три ситуации:

1. Всё хорошо
2. Число файлов меньше `minCount`
3. Размер файлов больше `maxSize`

Соответственно, по-хорошему, в этом классе должно быть (минимум) три теста: один, который должен срабатывать без исключений и два, от которых ожидается `MojoExecutionException` (вот тут небольшой туториал, как сделать тест, в котором ожидается исключение: https://www.mkyong.com/unittest/junit-4-tutorial-2-expected-exception-test/). Каждый тест оформляется отдельным методом, который желательно назвать не `testSomething`, а дать говорящее название, из которого ясно, какой именно случай тестируется. Сегодня как раз лекция про тестирование :)

2018-12-27 20:14 UTC, agorlenko commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +    private String minFileCount;
Можно сразу нужный тип указать.

2018-12-27 20:14 UTC, agorlenko commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +    private String maxFilesSize;
Аналогично. Можно сразу указать нужный тип.

2019-01-05 22:38 UTC, Afftobus commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +            for(File item : start.listFiles()){
обернул в try - catch

2019-01-05 22:39 UTC, Afftobus commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +                else{
поправил

2019-01-05 22:40 UTC, Afftobus commented on homework-maven-plugin/pom.xml
> +  <!-- FIXME change it to the project's website -->
в основной проект подключил свой плагин

2019-01-05 22:40 UTC, Afftobus commented on homework-maven-plugin/pom.xml
> +    <maven.compiler.source>1.7</maven.compiler.source>
ок

2019-01-05 22:40 UTC, Afftobus commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +public class TestFiles
поправил

2019-01-05 22:40 UTC, Afftobus commented on homework-maven-plugin/pom.xml
> +          <plugin>
ок

2019-01-05 22:41 UTC, Afftobus commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +import java.io.FileWriter;
ок

2019-01-05 22:41 UTC, Afftobus commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +        Long minCount = new Long(Integer.parseInt(minFileCount));
убрал махинации, у меня пока сложно с программированием на java

2019-01-05 22:42 UTC, Afftobus commented on homework-maven-plugin/src/test/java/hh/MyMojoTest.java
> +    public void testSomething()
убрал отсюда тесты вообще, подключил плагин к основному проекту

2019-01-05 22:42 UTC, Afftobus commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +    private String maxFilesSize;
ок

2019-01-08 17:35 UTC, alinkov requested changes

2019-01-08 17:35 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +            if (start.isDirectory()) {
методы нужно определять после параметров

и лучше переделать примерно таким образом
```suggestion
        private List<File> recursiveDirScan(File start) {
        if (!start.isDirectory()) {
            return Collections.emptyList();
        }
        List<File> result = new ArrayList<>();
        for (File item : Objects.requireNonNull(start.listFiles())) {
            if (item.isDirectory()) {
                result.addAll(recursiveDirScan(item));
            } else {
                result.add(item);
            }
        }
        return result;
    }
```

не очень хорошо, что изменяется входной параметр

2019-01-08 17:35 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +        System.out.println(scanDirectory);
пиши в лог

2019-01-08 17:35 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +        if (filelist.size() < minFileCount)
скобочек добавь.
в java они должны быть

2019-01-08 17:35 UTC, alinkov commented on homework-maven-plugin/src/main/java/hh/TestFiles.java
> +            if (start.isDirectory()) {
А вообще можно это сделать с помощью стандартных функций. 
Посмотри соседние PR

2019-01-11 15:44 UTC, alinkov approved these changes

2019-01-11 15:45 UTC, alinkov commented
Срок истек. Поэтому задачу засчитываю с недочетами

2019-01-11 15:45 UTC, closed without merging