Волгин Т.А. compress-maven-plugin
alinkov/maven-practice pull request #12
Opened 2018-12-26 20:56 UTC by TimaVolgin

2018-12-27 08:39 UTC, agorlenko commented on CompressMojo.java
> +    public void execute() throws MojoExecutionException, MojoFailureException {
Неиспользуемое исключение

2018-12-27 08:39 UTC, agorlenko commented on CompressMojo.java
> +            return FileVisitResult.CONTINUE;
Можно было бы наверно сообщать информацию по эксепшну в лог

2018-12-27 08:39 UTC, agorlenko commented on pom.xml
> +                    <source>1.7</source>
Версия >= 1.8

2018-12-27 08:56 UTC, alinkov requested changes
Проект не собирается

2018-12-27 08:56 UTC, alinkov commented on CompressMojo.java
> +package ru.volgin.maven.compress;
положи класс правильно.
В `src/main/java/...`

2018-12-27 08:56 UTC, alinkov commented on README.md
> +Архивация файлов
немногословно.
Хоть чуть-чуть описания параметров.
Можно в коде оставить

2018-12-27 09:02 UTC, fkhodkov reviewed
1. В таком виде плагин не собирается. Нужно, как минимум, положить java-файл в каталог src/main/java/дальше согласно названию пакета
2. Кстати, как называется пакет? `ru.volgin.maven.compress`, как сказано в .java или `dk.lockfuglsang.maven`, как следует из `groupId` в pom.xml? По идее, в обоих местах должно быть одно и то же.

2019-01-08 22:56 UTC, TimaVolgin commented on CompressMojo.java
> +    public void execute() throws MojoExecutionException, MojoFailureException {
Убрал

2019-01-08 22:57 UTC, TimaVolgin commented on pom.xml
> +                    <source>1.7</source>
Поправил

2019-01-08 22:57 UTC, TimaVolgin commented on CompressMojo.java
> +package ru.volgin.maven.compress;
Исправил

2019-01-08 22:57 UTC, TimaVolgin commented on README.md
> +Архивация файлов
Добавил описание

2019-01-09 08:07 UTC, alinkov requested changes

2019-01-09 08:07 UTC, alinkov commented on CompressMojo.java
> +package ru.volgin.maven.compress;
Что-то у тебя их 2 получилось

2019-01-09 08:07 UTC, alinkov commented on zip-maven-plugin/pom.xml
> +                    <source>1.8</source>
Используй ${jdk.version}

2019-01-09 08:07 UTC, alinkov commented on zip-maven-plugin/src/main/java/ru/volgin/maven/CompressMojo.java
> +            if (relative.toString().matches(pattern.replaceAll("\\*\\*", "*").replaceAll("\\*", ".*"))) {
зачем двойной replaceAll?
Используй регулярки
`.replaceAll("\\*+", "*")`

2019-01-09 08:07 UTC, alinkov commented on zip-maven-plugin/src/main/java/ru/volgin/maven/CompressMojo.java
> +        filename = filename.substring(0, filename.lastIndexOf('.')) + extension;
а что будет с файлами без разрешений?

2019-01-09 08:56 UTC, TimaVolgin commented on CompressMojo.java
> +package ru.volgin.maven.compress;
Проект не собирался после того как расположил файлы, поэтому взял POM из примера, который был в изначальном коммите и к нему подключил свой POM.

2019-01-09 08:58 UTC, TimaVolgin commented on CompressMojo.java
> +package ru.volgin.maven.compress;
Или речь идёт про CompressMojo.java? Просто при махинациях с парками и запуском, случайно удалил класс и снова добавил, git воспринял это как создание нового файла.

2019-01-09 20:15 UTC, TimaVolgin commented on zip-maven-plugin/src/main/java/ru/volgin/maven/CompressMojo.java
> +        filename = filename.substring(0, filename.lastIndexOf('.')) + extension;
поправил, теперь тоже добавляются в архив

2019-01-09 20:15 UTC, TimaVolgin commented on zip-maven-plugin/src/main/java/ru/volgin/maven/CompressMojo.java
> +            if (relative.toString().matches(pattern.replaceAll("\\*\\*", "*").replaceAll("\\*", ".*"))) {
поправил

2019-01-09 20:15 UTC, TimaVolgin commented on zip-maven-plugin/pom.xml
> +                    <source>1.8</source>
поправил

2019-01-09 20:15 UTC, TimaVolgin commented on CompressMojo.java
> +package ru.volgin.maven.compress;
удалил лишний

2019-01-10 07:54 UTC, alinkov commented on zip-maven-plugin/src/main/java/ru/volgin/maven/CompressMojo.java
> +        filename = filename.lastIndexOf('.') == -1 ? filename + extension: filename.substring(0, filename.lastIndexOf('.')) + extension;
вот лучше разделять все эти операции.
Лучше восприниматься будут и меньшая вероятность ошибок

2019-01-10 07:56 UTC, alinkov approved these changes

2019-01-10 07:56 UTC, alinkov commented
Засчитываю с некоторыми недочетами

2019-01-10 07:56 UTC, closed without merging