Колесникова Ксения check-files-maven-plugin
alinkov/maven-practice pull request #13
Opened 2018-12-26 21:47 UTC by K-ksenia

Создан плагин, который считает и выводит количество файлов в директории. Если полученное число меньше заданного, то также выводится детализация (в формате `Каталог <путь к директории> содержит <число> подкаталогов и <число> файлов.`) для каждой директории внутри заданной.

2018-12-27 08:02 UTC, k-vasiliev commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private int getCount(File Directory) {
Обычно переменные называют с маленькой буквы. Одна из причин - когда ты ниже делаешь Directory.listFiles() создается впечатление, что ты вызываешь статический метод класса, а это не так.

Вообще весь метод можно заменить на 
`new File(directory).list().length`

И еще нужно не забыть проверить есть ли у тебя доступ к папке, null там может быть как раз в этой ситуации

2018-12-27 08:04 UTC, k-vasiliev commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        assert listFiles != null;
А почему? :) Если у тебя нет доступа к папке или в ней нет файлов - это вполне нормальная ситуация для твоего плагина, на сколько я понял. assert довольно жесткая штука, он точно тут нужен?

2018-12-27 08:08 UTC, k-vasiliev commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        System.out.println("Directory " + Directory + " contains " + directoryCount + " subdirectories and " + filesCount + " files.");
В Java есть такая штука, как String.format(), её удобно применять как раз в таких ситуациях, чтобы не использовать + ". 
Строка превращается в 
`("Directory %s contains %s subdirectories and %s files.", Directory, directoryCount, filesCount)`

2018-12-27 08:15 UTC, k-vasiliev commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private void getDetailing(File Directory) {
Вообще считается не очень хорошей практикой называть метод get..., а потом ничего не возвращать. Я бы назвал метод print..., либо создал объект типа FileDetail и вернул его

2018-12-27 08:19 UTC, k-vasiliev commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        int countFiles = getCount(new File(path));
Наверно не критично, но ты проходишь рекурсивно дважды по файловой структуре - сначала считаешь файлы, а потом еще раз выводишь информацию о них. Можно обойтись одним проходом

2018-12-27 08:36 UTC, fkhodkov commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private String count;
Не обязательно объявлять все параметры как `String`, можно объявить `private File path` и `private Integer count`, тогда `new File(path)` и `Integer.parseInt(count)` будут сделаны автоматически (см. https://maven.apache.org/guides/plugin/guide-java-plugin-development.html#Configuring_Parameters_in_a_Project).

2018-12-27 08:37 UTC, agorlenko requested changes

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private String path;
Можно вот так прям: private File path;

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private String count;
ну и здесь: private int count;

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        System.out.println("-------------------------------------------------------------------------------");
имхо, лучше выводить явно с классификацией: getLog().info(), getLog().error()

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private int getCount(File Directory) {
Название переменной не в стиле java

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +            if (subFile.isFile()) {
Тут насколько помню исключение будет, если на файл нет прав.

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +            if (subFile.isFile()) {
Тут насколько помню исключение будет, если на файл нет прав.

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        for (File subFile : listFiles) {
Возможно, проще через Files.walk() или Files.walkFileTree() ?

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/pom.xml
> +                        <!--<release>${jdk.version}</release>--><!--TODO uncomment this line, if you use Java9+ or delete-->
Все-таки надо бы сделать TODO )

2018-12-27 08:37 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    @Parameter(property = "path", defaultValue = "./")
Нет комента для параметра, который в help транслироваться будет.

2018-12-27 09:05 UTC, alinkov requested changes
Тут столько комментариев написали.
Спасибо ребятам)

Для стиля кода добавь checkstyle plugin

2018-12-27 09:05 UTC, alinkov commented on pom.xml
> +  <modules>
модули лучше в самом начале объявлять

2018-12-27 11:08 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        assert listFiles != null;
А мне его просто IntelliJ предложил, я и согласилась😅 так как не поняла, что не так то. Исправлю, спасибо)

2018-12-27 12:03 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        for (File subFile : listFiles) {
Возможно) Но так как я первый раз на джаве пишу, для меня было понятнее так 🤷‍♀️

2018-12-27 12:04 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private int getCount(File Directory) {
Поправила, спасибо

2018-12-27 12:12 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        System.out.println("-------------------------------------------------------------------------------");
Оки

2018-12-27 12:15 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private String count;
О, то что нужно! Спасибо

2018-12-27 12:18 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    @Parameter(property = "path", defaultValue = "./")
Переделала комменты непосредственно перед каждым параметром

2018-12-27 12:23 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        int countFiles = getCount(new File(path));
Да, я думала об этом. Но программа знает выводить или нет детализацию только когда уже получит итоговый filesCount. В первом обходе мы его еще не знаем, и, соответсвенно, не знаем нужно ли выводить инфу. 
А как еще это можно реализовать, я не придумала

2018-12-27 12:24 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +    private void getDetailing(File Directory) {
Угу, логично, спасибо!)

2018-12-27 12:27 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        System.out.println("Directory " + Directory + " contains " + directoryCount + " subdirectories and " + filesCount + " files.");
👌

2018-12-27 13:01 UTC, k-vasiliev commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +        int countFiles = getCount(new File(path));
Можно складывать сообщения в очередь, а в лог выводить не в процессе проверки файлов, а после окончания проверки. Как только счетчик файлов превысит определенное значение - ты знаешь, что очередь можно очистить и ничего туда не добавлять. Как бы да, тебе придется пройтись по всем сообщениям, но это отличается по скорости от чтения с диска. Еще вариант - считать не все файлы, останавливаться после твоего лимита (тебе же достаточно знать нужно ли выводить инфу или нет, а не знать точное количество файлов)

2019-01-02 21:03 UTC, agorlenko commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +            return;
Собирается, работает, но вот в этом случае немного странно получается: в логе сборке красные ERROR, но в итоге сборка успешная. Возможно в этом случае логичнее это как WARNING выдавать (ну или сборку неуспешной считать, зависит от того, как ты такие ситуации интерпретируешь)?

2019-01-02 23:00 UTC, K-ksenia commented on check-files-maven-plugin/src/main/java/ru/hh/school/CheckFilesMojo.java
> +            return;
Логично, сделала WARNING

2019-01-09 15:59 UTC, alinkov approved these changes

2019-01-09 15:59 UTC, alinkov commented
Засчитано

2019-01-09 15:59 UTC, closed without merging