Горленко Алексей
alinkov/maven-practice pull request #2
Opened 2018-12-20 23:36 UTC by agorlenko

Плагин для проверки размера файлов в указанной директории.

2018-12-21 14:26 UTC, alinkov requested changes
Плагин всегда падает с ошибкой.

2018-12-21 14:26 UTC, alinkov commented on src/main/java/ru/hh/school/plugins/file_size_control_plugin/FileSizeControlMojo.java
> +package ru.hh.school.plugins.file_size_control_plugin;
в java package так не называют
речь про `file_size_control_plugin`

2018-12-21 14:26 UTC, alinkov commented on src/main/java/ru/hh/school/plugins/file_size_control_plugin/FileSizeControlMojo.java
> +        throws MojoExecutionException, MojoFailureException {
лишние исключения лучше подчищать

2018-12-21 14:26 UTC, alinkov commented on src/main/java/ru/hh/school/plugins/file_size_control_plugin/FileSizeControlMojo.java
> +    class FileVerifier extends SimpleFileVisitor<Path> {
приватные классы лучше делать в конце

2018-12-21 22:03 UTC, agorlenko commented on src/main/java/ru/hh/school/plugins/file_size_control_plugin/FileSizeControlMojo.java
> +package ru.hh.school.plugins.file_size_control_plugin;
Поправил.

2018-12-21 22:04 UTC, agorlenko commented on src/main/java/ru/hh/school/plugins/file_size_control_plugin/FileSizeControlMojo.java
> +        throws MojoExecutionException, MojoFailureException {
Поправил.

2018-12-21 22:04 UTC, agorlenko commented on src/main/java/ru/hh/school/plugins/file_size_control_plugin/FileSizeControlMojo.java
> +    class FileVerifier extends SimpleFileVisitor<Path> {
Поправил.

2018-12-22 08:53 UTC, agorlenko commented
Исправил генерацию ошибки при любой сборке.

2018-12-24 07:37 UTC, alinkov commented
Засчитано

2018-12-24 07:37 UTC, closed without merging