Еремейкин Пётр Александрович. Вариант 1. Разработка плагина для создания дампа mysql БД.
alinkov/maven-practice pull request #4
Opened 2018-12-23 13:07 UTC by eremeykin

# Работа с maven
### Вариант 1
Разработка maven плагина, который делает дамп mysql базы данных.
Для работы плагина потребуется уставновленная утилита `mysqldump`.
Но так как плагин позволяет сконфигурировать команду, которая 
будет играть роль `mysqldump`, то его можно запустить в режиме имитации,
то есть вместо настоящей `mysqldump` подставить самописный скрипт 
`mysqldump.sh`, который имитирует создание дампа.

Репозиторий:
* `src/it` - интеграционный тест
* `src/main` - исходники плагина
* `src/test` - исходники тестов

Сборка и деплой: `mvn deploy`

Выполнение: `mvn dump:dump`

Краткая справка: `mvn dump:help`

Полная справка: `mvn dump:help -Ddetail=true -Dgoal=dump`

    dump:dump
      Создает дапм базы данных MySql. Для работы необходимо установленная утилита
      mysqldump. Для тестирования она заменена мок скриптом mysqldump.sh, который
      имитирует работу mysqldump.
      Available parameters:
    
        completeInsert (Default: true)
          Использовать полные выражения вставки.
    
        dbName (Default: database)
          Название базы данных
          Required: Yes
    
        exec (Default: mysqldump)
          Команда для исполнения mysqldump. Через этот параметр можно подменить
          выполнение настоящей mysqldump скриптом mysqldump.sh, который имитирует
          работу mysqldump.
    
        extendedInsert (Default: true)
          Использовать синтексис INSERT, который позволяет включать несколько
          списков значений.
    
        host (Default: localhost)
          Хост сервера СУБД
          Required: Yes
    
        outputFile (Default: dump.sql)
          Файл в который запишется дамп
          User property: mySqlDump
    
        password (Default: mysql)
          Пароль для подключения к серверу СУБД
          Required: Yes
    
        port (Default: 3306)
          Порт сервера СУБД
          Required: Yes
    
        quoteNames (Default: true)
          Экранировать названия таблиц и столбцов, например, `tablename`.`colname`
    
        singleTransaction (Default: true)
          В одной транзакции, только для InnoDB.
    
        userName (Default: root)
          Имя пользователя для подключения к серверу СУБД
          Required: Yes

2018-12-24 08:18 UTC, alinkov requested changes
Идея хорошая и тесты есть и описание.
Вот только надо немного поправить.

2018-12-24 08:18 UTC, alinkov commented on src/main/java/pete/eremeykin/DumpMojo.java
> +     * @parameter
Зачем это?
В javadoc называется @param и описывается. Если пусто, то лучше удалять

2018-12-24 08:18 UTC, alinkov commented on src/main/java/pete/eremeykin/DumpMojo.java
> +    @Parameter(defaultValue = CMD_DUMP)
нужно задать название параметра

2018-12-24 08:18 UTC, alinkov commented on src/test/java/pete/eremeykin/ConfigTest.java
> +        customFilePaths.put(PARAM_BASE_DIR, "/bin");
зачем в /bin ?
так тесты ни у кого не пройдут

2018-12-24 18:12 UTC, eremeykin commented on src/main/java/pete/eremeykin/DumpMojo.java
> +     * @parameter
Видел такое в справке по документированию maven плагинов. 
https://maven.apache.org/guides/development/guide-plugin-documentation.html 

> all @parameter fields should have a descriptive comment, informative enough that even a regular user can understand
> 
>         [...]
>         /**
>          * Put something informative here that a regular user can understand.
>          * 
>          * @parameter 
>          */
>         private boolean someparameter;
>         [...]

Решил что так делается для того чтобы javadoc сам встал в справку по параметру на стадии site. Но похоже это не нужно, убрал в 53900f6

2018-12-24 18:33 UTC, eremeykin commented on src/test/java/pete/eremeykin/ConfigTest.java
> +        customFilePaths.put(PARAM_BASE_DIR, "/bin");
Дело в доступе? Заменил на /tmp в 99a8ab6. В /tmp у всех же есть доступ?

2018-12-24 19:45 UTC, eremeykin commented on src/main/java/pete/eremeykin/DumpMojo.java
> +    @Parameter(defaultValue = CMD_DUMP)
Добавил имена свойств `property = <fieldName>` для всех параметров в b397d00. Названия т.е. `name` мне кажется уместно оставить по-умолчанию т.е. имя поля:

    /**
     * name of the bean property used to get/set the field: by default, field name is used.
     * @return the name of the bean property
     */
    String name() default "";

2018-12-25 16:19 UTC, alinkov requested changes
Поправь момент с не прохождением тестов по умолчанию и зачту задачку

Если что, проблема с доступом при запуске скрипта.

2018-12-25 18:06 UTC, eremeykin commented
Теперь должно работать. Нужен был `chmod +x` для `mysqldump.sh` и причем после того как он будет скопирован в `/target`. Добавил еще один плагин в `pom` который делает `chmod` на фазе `process-test-resources`, после этого на моей машине тесты в свежем клоне проходят.

2018-12-26 12:00 UTC, alinkov commented
Тесты прошли. Засчитываю

2018-12-26 12:00 UTC, closed without merging

2018-12-26 15:59 UTC, alinkov commented on src/main/java/pete/eremeykin/DumpMojo.java
> +     * @parameter
@parameter похоже нужно задавать, если над методом не стоит аннотация @parameter.
Но это нужно проверить

2018-12-26 16:01 UTC, alinkov commented on src/main/java/pete/eremeykin/DumpMojo.java
> +    @Parameter(defaultValue = CMD_DUMP)
Тут я вел речь именно про property