Rudakov Evgeny - Variant 1 - Make Maven plugin project
alinkov/maven-practice pull request #5
Opened 2018-12-23 21:25 UTC by dolphin-in-a-coma

Плагин проверяет, какие файлы  в /scr были изменены после последнего билда, и выводит их. 
Есть два параметра:
            onjyJava (boolean) - если true, ищет только *.java файлы;
            maxAmount (int) - ограничивает максимальный вывод измененных файлов.

2018-12-24 14:46 UTC, alinkov requested changes
Необходимо внести небольшие корректировки

2018-12-24 14:46 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +    @Parameter(defaultValue = "${project.build.directory}", readonly = true)
нужно сделать так, чтобы параметры можно было задавать через -D при запуске из консоли

2018-12-24 14:46 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            File packageFile = new File(outputDirectory, project.getName() + '-' +project.getVersion() + '.' + project.getPackaging());
имя не обязательно такое. Оно может быть переопределено в настройках

2018-12-24 14:46 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            RegexFileFilter fileFilter = new RegexFileFilter(".*");
```suggestion
             RegexFileFilter fileFilter = onlyJava ? new RegexFileFilter(".*java") : new RegexFileFilter(".*");
```

2018-12-24 14:46 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            changedFiles.sort((File a, File b)-> a.lastModified() >  b.lastModified() ? -1 :  1);
лучше переделать через стримы.
Получится более красивый вариант

2018-12-24 21:53 UTC, dolphin-in-a-coma commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            changedFiles.sort((File a, File b)-> a.lastModified() >  b.lastModified() ? -1 :  1);
Переделал

2018-12-24 21:56 UTC, dolphin-in-a-coma commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            File packageFile = new File(outputDirectory, project.getName() + '-' +project.getVersion() + '.' + project.getPackaging());
Поправил, теперь ищет последний пакедж в таргете, не делая предположения о его названии в jar или project.getPackaging() формате. jar дополнительно добавлен на случай неявного указания упаковки, как например в случае сборки плагина, где project.getPackaging() будет возвращать plugin, а формат упаковки на деле будет jar.

2018-12-24 21:56 UTC, dolphin-in-a-coma commented
Спасибо, все поправил, кроме возможности задать параметр через -D в строке. Как мне кажется организовал параметры согласно документации, но почему-то не работает. Может есть еще какие-нибудь источники к которым можно обратиться, чтобы прояснить почему так? У меня не получилось на них выйти.

2018-12-25 16:12 UTC, alinkov commented
> Спасибо, все поправил, кроме возможности задать параметр через -D в строке. Как мне кажется, организовал параметры согласно документации, но почему-то не работает. Может есть еще какие-нибудь источники, к которым можно обратиться, чтобы прояснить почему так? У меня не получилось на них выйти.

Должно быть достаточно задать имя в аннотации @Parameter

2018-12-25 16:27 UTC, alinkov requested changes
Добавь модуль в основной проект

2018-12-25 16:27 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            RegexFileFilter fileFilter = onlyJava ? new RegexFileFilter(".*java") : new RegexFileFilter(".*");
org.apache.commons.io.filefilter.SuffixFileFilter лучше подходит

2018-12-27 21:24 UTC, dolphin-in-a-coma commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            RegexFileFilter fileFilter = onlyJava ? new RegexFileFilter(".*java") : new RegexFileFilter(".*");
Заменил

2018-12-27 21:25 UTC, dolphin-in-a-coma commented
Все поправил

2018-12-27 23:52 UTC, agorlenko commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +import java.util.*;
По идее можно без импорта со "*" обойтись

2018-12-28 07:51 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +import java.util.*;
и без лишних импортов)

2018-12-28 07:55 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +                .get()
orElseThrow

2019-01-09 16:07 UTC, alinkov requested changes

2019-01-09 16:07 UTC, alinkov commented on recenly-changes-maven-plugin/src/main/java/com/hh/homework/maven/RecentlyChangesMojo.java
> +            Long packageTime = FileUtils.listFiles(outputDirectory, projectTypes, true).stream()
нужно сделать проверку на то, что это директория

2019-01-11 15:49 UTC, alinkov approved these changes

2019-01-11 15:49 UTC, alinkov commented
Срок истек. Поэтому засчитываю то, что есть

2019-01-11 15:49 UTC, closed without merging