Сулим Hometask_Maven
alinkov/maven-practice pull request #6
Opened 2018-12-24 06:14 UTC by SuhoyVasya

2018-12-25 16:10 UTC, alinkov requested changes
Тут checkstyle проходит?
Если да. то видимо мягковатые правила.

Плагин инетерсный, но код немного нужно привести в порядок

2018-12-25 16:10 UTC, alinkov commented on src/test/java/TestEncrypting.java
> +        {
давай придерживаться рекомендаций от оракла по написанию кода и писать  `{` на той же строке
И хоршо бы пробельчиков добавить

2018-12-25 16:10 UTC, alinkov commented on src/main/java/ArgumentsUtils.java
> +            if ("-p".equals(args[i])) {
лучше параметры в Set завернуть и смотреть на наличие

2018-12-25 16:10 UTC, alinkov commented on src/test/java/TestArgumentsUtils.java
> +    public void tearDown() {
лучше пустые методы не добавлять

2018-12-25 16:10 UTC, alinkov commented on src/main/java/secure/KeysUtils.java
> +            stream.close();
лучше try with resources, а то возможно незакрытие ресурсов

2018-12-26 05:39 UTC, SuhoyVasya commented on src/main/java/ArgumentsUtils.java
> +            if ("-p".equals(args[i])) {
В Set нельзя - порядок следования некоторых аргументов играет роль. Могу переписать с использованием List, но аккуратности кода кардинально не прибавится.

2018-12-26 05:56 UTC, SuhoyVasya commented on src/main/java/secure/KeysUtils.java
> +            stream.close();
все операции с потоками ввода-вывода переписал через конструкции try-with-resources.

2018-12-26 05:56 UTC, SuhoyVasya commented on src/test/java/TestArgumentsUtils.java
> +    public void tearDown() {
Пустые методы в тестах убрал.

2018-12-26 05:56 UTC, SuhoyVasya commented on src/test/java/TestEncrypting.java
> +        {
Код отформатировал внутренними средствми IDEA.

2018-12-26 15:17 UTC, alinkov requested changes
необходимо настроить checkstyle плагин.
Стиль кода хворает.
Также можно попробовать статистический анализатор кода

2018-12-26 15:17 UTC, alinkov commented on pom.xml
> +            <plugin>
```suggestion
                         <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.0.0</version>
                <dependencies>
                    <dependency>
                        <groupId>com.github.sevntu-checkstyle</groupId>
                        <artifactId>sevntu-checkstyle-maven-plugin</artifactId>
                        <version>1.32.0</version>
                    </dependency>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>8.12</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <configuration>
                            <sourceDirectories>
                                <sourceDirectory>${basedir}/src</sourceDirectory>
                            </sourceDirectories>
                            <configLocation>config/checkstyle.xml</configLocation>
                            <encoding>UTF-8</encoding>
                            <includeTestSourceDirectory>true</includeTestSourceDirectory>
                            <violationSeverity>error</violationSeverity>
                            <consoleOutput>true</consoleOutput>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

2018-12-26 15:17 UTC, alinkov commented on src/main/java/ArgumentsUtils.java
> +import exceptions.EncoderFileException;
помести все классы в какой-нибудь package

2018-12-26 15:17 UTC, alinkov commented on src/main/java/Encoder.java
> +    public static void main(String[] args) {
разбей метод

2018-12-27 11:55 UTC, SuhoyVasya commented on pom.xml
> +            <plugin>
Настроил checkstyle на правила по-умолчанию. Проверку некоторых подавил фильтром.

2018-12-27 11:56 UTC, SuhoyVasya commented on src/main/java/ArgumentsUtils.java
> +import exceptions.EncoderFileException;
поместил весь проект в пакет hhtask

2018-12-27 11:56 UTC, SuhoyVasya commented on src/main/java/Encoder.java
> +    public static void main(String[] args) {
разбил метод main на два

2018-12-28 07:49 UTC, alinkov reviewed
Домашнее задание зачитываю.
Т.к. были недочеты, оценка не максимальная.
Если хочется получить оценку выше, то можно поучаствовать в ревью. За это оценка будет повышена

2018-12-28 07:49 UTC, alinkov commented on src/main/java/hhtask/Encoder.java
> +            System.err.println(e.getMessage());
а зачем и в логгер и в System.out?

2018-12-28 07:49 UTC, alinkov commented on src/main/java/hhtask/Encoder.java
> +        PlainFile plainFile = new PlainFile(plainPath);
дублирующуюся участки лучше выносить в отдельные методы

2018-12-28 07:49 UTC, alinkov commented on src/main/java/hhtask/Encoder.java
> +            log.error("Help file not found");
будет NPE а не IOException
java.lang.ClassLoader#getResourceAsStream возвращает null

2018-12-28 07:49 UTC, closed without merging

2018-12-28 08:55 UTC, SuhoyVasya commented on src/main/java/hhtask/Encoder.java
> +            System.err.println(e.getMessage());
Приложение задумывалось как консольное. Основные оповещения выводятся в консоль. В логгер  попадают еще некоторые ошибки.

2018-12-28 08:56 UTC, SuhoyVasya commented on src/main/java/hhtask/Encoder.java
> +        PlainFile plainFile = new PlainFile(plainPath);
Спасибо, учту.