Никишин А.А.
alinkov/maven-practice pull request #7
Opened 2018-12-25 12:06 UTC by anickishin

2018-12-25 16:11 UTC, alinkov requested changes
Хоть какое-то описание нужно сделать

2018-12-26 15:24 UTC, alinkov requested changes
Не удалось запустить плагин с настройками по умолчанию

2018-12-26 15:24 UTC, alinkov commented on src/main/java/NamingMojo.java
> +package ru.hh.school;
package указан, а сам файл лежит не там

2018-12-27 09:56 UTC, alinkov requested changes
Нужно сделать, чтобы плагин работал по умолчанию. Сейчас он падает

2018-12-27 09:56 UTC, alinkov commented on src/main/java/ru/hh/school/NamingMojo.java
> +    @Parameter(defaultValue = "Target", property = "classTarget")
неправильное значение по умолчанию

2018-12-29 08:58 UTC, agorlenko commented on src/main/java/ru/hh/school/NamingMojo.java
> +            Vector<String> classList = new Vector<String>();
Vector тебе здесь точно нужен? Без явной необходимости им лучше не пользоваться.

2018-12-29 08:58 UTC, agorlenko commented on src/main/java/ru/hh/school/NamingMojo.java
> +import java.nio.file.*;
Лучше подчистить неиспользуемые импорты и без необходимости не пользоваться импортом со "*"

2018-12-29 09:16 UTC, agorlenko commented on src/main/java/ru/hh/school/NamingMojo.java
> +            if (entry.isDirectory())
Что если на файл или папку нет прав?

2018-12-29 09:16 UTC, agorlenko commented on src/main/java/ru/hh/school/NamingMojo.java
> +                            if (classList.size()<2) {
Неплохо бы добавить checkstyle

2018-12-31 10:00 UTC, alinkov requested changes
Необходимо привести код в порядок.
Очень рекомендую подключить checkstyle plugin + поправить ошибки статического анализатора кода

2018-12-31 10:00 UTC, alinkov commented on src/main/java/ru/hh/school/NamingMojo.java
> +                        try {
такую вложенность делать не стоит.
Нужно точно разбить на отдельные методы

2019-01-11 15:46 UTC, alinkov approved these changes

2019-01-11 15:47 UTC, alinkov commented
Срок истек. Засчитываю с некоторыми недочетами.
Если будет желание можно будет их поправить и напиши в личку (до конца выходных)

2019-01-11 15:47 UTC, closed without merging