Васильев К.А
alinkov/maven-practice pull request #8
Opened 2018-12-25 17:39 UTC by k-vasiliev

Плагин для поиска стоп-слов в коде проекта (актуально в связи с последними новостями в Linux-сообществе).

### Конфигурация
**stopWords**
Список из стоп-слов, которые будут искаться в коде

**excludes**
Список папок/файлов, которые будут исключены из поиска

**errorLevel**
Принимает значение "WARN" и "ERROR". В случае "WARN" просто пишет предупреждения в консоль, в случае "ERROR" если были найдены стоп-слова, то прекращает сборку

**ignoreCase**
Нужно ли игнорировать кейс

### Кэширование
В плагине реализовано кэширование, которое позволяет не просматривать файлы, которые не были изменены с прошлого запуска плагина.

### Пример использования
**В pom.xml**
```
<plugin>
    <groupId>sample.plugin</groupId>
    <artifactId>stoplist-maven-plugin</artifactId>
    <version>1.0.1</version>
    <configuration>
        <errorLevel>WARN</errorLevel>
        <ignoreCase>true</ignoreCase>

        <excludes>
            <exclude>.idea</exclude>
            <exclude>./target</exclude>
            <exclude>./pom.xml</exclude>
        </excludes>

        <stopWords>
            <stopWord>javaScript</stopWord>
        </stopWords>
    </configuration>
    <executions>
        <execution>
            <id>on-compile</id>
            <phase>compile</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Из консоли**
`$ mvn sample.plugin:stoplist-maven-plugin:check -DstopWords=javaScript,php -Dexcludes=pom.xml,.idea -DerrorLevel=ERROR`

2018-12-26 14:49 UTC, alinkov requested changes
Настрой checkstyle plugin и посмотри каким-нибудь статическим анализатором.
Они подскажут, как можно сделать правильно некоторые вещи.

2018-12-26 14:49 UTC, alinkov commented on src/main/java/sample/plugin/MapInFileCache.java
> +    private String FILE_CACHE_PATH = "target/plugins-cache/stop-list/last-modified-files.cache";
`target/` лучше параметром. Может по-другому называться

2018-12-26 14:49 UTC, alinkov commented on src/main/java/sample/plugin/StopListMojo.java
> +                    if (ignoreCase) {
такую вложенность лучше не делать

2018-12-26 14:49 UTC, alinkov commented on src/main/java/sample/plugin/MapInFileCache.java
> +    private String FILE_CACHE_PATH = "target/plugins-cache/stop-list/last-modified-files.cache";
и сделай static final

2018-12-26 14:49 UTC, alinkov commented on src/main/java/sample/plugin/MapInFileCache.java
> +            FileInputStream inputStream = new FileInputStream(FILE_CACHE_PATH);
try with resources

2018-12-26 14:49 UTC, alinkov commented on pom.xml
> +        <maven.compiler.source>1.7</maven.compiler.source>
а зачем тут 7, а в компиляторе 8?

2018-12-26 14:49 UTC, alinkov commented on src/test/java/sample/plugin/StopListMojoTest.java
> +        File pom = new File("target/test-classes/project-to-test/");
из таргета лучше не вытягивать в тестах.
Вытягивай из ресурсов

2018-12-26 14:49 UTC, alinkov commented on pom.xml
> +        <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
Если нет дочерних модулей, то не особо хорошо использовать и pluginManagement и plugins.
Просто получается в двух местах объявления, а это создано для того, чтобы избегать дублирования

2018-12-26 14:49 UTC, alinkov commented on src/main/java/sample/plugin/MapInFileCache.java
> +import java.io.*;
Я стараюсь * не использовать, с ними потом проблемы могут быть

2018-12-26 14:49 UTC, alinkov commented on src/main/java/sample/plugin/MapInFileCache.java
> +            cacheFile.createNewFile();
Можно использовать FIleUtils от Apache. Там есть много полезных методов для работы с файлами

2018-12-26 19:00 UTC, k-vasiliev commented on pom.xml
> +        <maven.compiler.source>1.7</maven.compiler.source>
В свое оправдание могу сказать, что это осталось из архетипа для создания плагина, а я не перепроверял его детально. Поправлю, конечно

2018-12-27 09:47 UTC, alinkov requested changes

2018-12-27 09:47 UTC, alinkov commented on src/main/java/sample/plugin/StopListMojo.java
> +    String fileName = file.getName();
лучше попробовать все это сделать через java.io.FilenameFilter
получится более понятный код

2018-12-27 09:47 UTC, alinkov commented on src/test/java/sample/plugin/StopListMojoTest.java
> +    File pom = new File("src/test/resources/project-to-test/");
`new File(getClass().getResource("pom.xml").getFile())`
я примерно так имел ввиду
для этого нужно будет перенести pom.xml в нужный пакет

2018-12-27 11:06 UTC, k-vasiliev commented on src/main/java/sample/plugin/StopListMojo.java
> +    String fileName = file.getName();
Я попробовал, мне не нравится вариант с FileNameFilter.
1) Лишняя итерация по массиву файлов - сейчас я проверяю и контент и название файла за один проход
2) После работы FileNameFilter у меня на руках массив из файлов, при этом какое конкретно стоп-слово какой файл содержит не ясно. Я могу логировать прям внутри FileNameFilter, но мне не кажется это хорошим решением

2018-12-27 13:49 UTC, alinkov commented
Засчитываю.
И спасибо за активное участие в ревью

2018-12-27 13:49 UTC, closed without merging