Рогожинский Константин, задание по maven
alinkov/maven-practice pull request #9
Opened 2018-12-26 00:44 UTC by rogozhinski

## Домашнее задание по maven

	В качестве направления домашнего задания выбран второй вариант - создание приложения.

## Описание приложения

	Приложение предназначено для выполнения расчетов на основе некоторых из основных физических формул, среди которых:
	- второй закон Ньютона;
	- уравнение гидростатического давления;
	- закон Ома;
	- выражение для энергии конденсатора.

	Приложение работает в консольном режиме и управляется с помощью численных значений, вводимых пользователем с клавиатуры. Случаи некорректного ввода обрабатываются.

## Сложности 

	1. На данный момент возникла сложность с запуском jar-файла. Несмотря на удачную компиляцию проекта и сборку .jar, запуск последнего приводит к следующей ошибке:

	"Error: Could not find or load main class com.Application"

	При этом в POM'e все ссылки на основной класс приложения заменены на актуальные. Попытки запуска вне IDE (с консоли ОС) не приводят к успеху

	2. Ввиду отсутствия опыта в подготовке тестов, они на данный момент находятся все еще на стадии разработки. В частности, трудности вызвала потребность в эмуляции ввода с клавиатуры.

2018-12-26 10:15 UTC, k-vasiliev commented
По поводу запуска - у тебя в pom-е <mainClass>com.Application</mainClass>, а реальный пакет main.java.com.Application. Попробуй пофиксить, возможно из за этого не запускается

2018-12-26 10:16 UTC, k-vasiliev commented on src/main/java/com/Application.java
> +        MainInterface app_interface = new MainInterface();
Вообще в Java не принят snake_case, это касается как названий переменных, так и методов

2018-12-26 10:21 UTC, k-vasiliev commented on src/main/java/com/app_interface/MainInterface.java
> +    public void choosing_physics_branch() {
Метод называется choosing_..., но на самом деле он помимо выбора еще и производит все вычисления. Как вариант предложил бы handleUserInput()

2018-12-26 10:23 UTC, rogozhinski commented on src/main/java/com/Application.java
> +        MainInterface app_interface = new MainInterface();
Это питоновские замашки.

2018-12-26 10:25 UTC, rogozhinski commented on src/main/java/com/app_interface/MainInterface.java
> +    public void choosing_physics_branch() {
Сам метод не производит вычисления, а скорее направляет к тем методам, которые производят (последние имеют в названии постфикс «computation»).

2018-12-26 10:35 UTC, k-vasiliev commented on src/main/java/com/app_interface/mechanics_interface/InertiaLawInterface.java
> +public class InertiaLawInterface {
Вообще в Java есть интерфейсы, которые нужно имплементить. Когда ты называешь обычный класс интерфейсом, то это может ввести других в заблуждение. Как вариант -  вместо ...Interface можно использовать ...UI, в твоем случае даже ...ConsoleUI

2018-12-26 10:51 UTC, k-vasiliev commented on src/main/java/com/electrodynamics/CapacitorEnergy.java
> +    public CapacitorEnergy (double e, double c, double u) {
У тебя расчеты всегда происходят по двум полям, а конструктор принимает три поля, поэтому одно из значений тебе всегда придется передавать 0 и реально оно не будет использоваться. Я бы вообще отказался от не-дефолтного конструктора и параметры передавал бы сразу в методы

2018-12-26 10:54 UTC, rogozhinski commented on src/main/java/com/electrodynamics/CapacitorEnergy.java
> +    public CapacitorEnergy (double e, double c, double u) {
Мне нужно было 10+ классов. :)

2018-12-26 10:56 UTC, k-vasiliev commented on src/main/java/com/electrodynamics/OhmLaw.java
> +    public double current_strength_computation() {return voltage / resistance;}
Было бы неплохо добавить проверку на 0 во всех вычислениях

2018-12-26 11:06 UTC, k-vasiliev commented on src/test/TestSet.java
> +//package test;
Если весь класс закоменчен, то может нет смысла его класть в гит?

2018-12-26 11:13 UTC, k-vasiliev commented on pom.xml
> +            <artifactId>jetty-server</artifactId>
Тебе это точно тут нужно? :)

2018-12-26 11:17 UTC, k-vasiliev commented on src/main/java/com/app_interface/MyUtils.java
> +    public static boolean isDigit (String input) throws NumberFormatException {
Ты уверен, что этот метод тебе нужен? Ты делаешь тут try-catch, возвращаешь boolean, а потом делаешь if-else в зависимости от этого значения. Почему бы сразу не сделать try-catch в месте, где происходит input?

2018-12-26 11:19 UTC, rogozhinski commented on src/main/java/com/app_interface/MyUtils.java
> +    public static boolean isDigit (String input) throws NumberFormatException {
Управление сложностью дроблением кода.

2018-12-26 11:31 UTC, k-vasiliev commented on pom.xml
> +            <id>classic</id>
Ты уверен, что тебе тут нужны профили? Я просто не нашел их использования где-либо

2018-12-26 11:32 UTC, k-vasiliev commented on pom.xml
> +            <groupId>log4j</groupId>
Ты подтянул логгер, но вместо него используешь system.out. Не надо так

2018-12-26 11:35 UTC, k-vasiliev commented on pom.xml
> +          <artifactId>maven-checkstyle-plugin</artifactId>
Попробуй запустить этот плагин на твоем проекте =)

2018-12-26 11:38 UTC, k-vasiliev commented on src/main/java/com/Application.java
> +        MainInterface app_interface = new MainInterface();
Да понятно :) Но на реальном проекте если будешь писать в camel-case, то тебя не поймут

2018-12-26 11:41 UTC, k-vasiliev commented on src/main/java/com/app_interface/MainInterface.java
> +    public void choosing_physics_branch() {
Да, но внутри него все равно по-факту производятся вычисления? Из хорошего названия метода понятно либо что он возвращает, либо что он делает, в данном случае это не прозрачно :)

2018-12-26 11:42 UTC, k-vasiliev commented on src/main/java/com/electrodynamics/CapacitorEnergy.java
> +    public CapacitorEnergy (double e, double c, double u) {
Так я не предлагаю избавляться от всего класса, только от конструктора

2018-12-26 11:43 UTC, k-vasiliev commented on src/main/java/com/app_interface/MyUtils.java
> +    public static boolean isDigit (String input) throws NumberFormatException {
Так в данном случае нет дробления, только увеличение его количества в два раза

2018-12-26 11:46 UTC, rogozhinski commented on src/main/java/com/app_interface/MyUtils.java
> +    public static boolean isDigit (String input) throws NumberFormatException {
Да, действительно.

2018-12-26 15:37 UTC, alinkov requested changes
Большой совет настроить checkstyle plugin + посмотреть на код статическим анализатором

2018-12-26 15:37 UTC, alinkov commented on pom.xml
> +            <version>2.8.4</version>
в константу

2018-12-26 15:37 UTC, alinkov commented on src/main/java/com/Application.java
> +package main.java.com;
package везде указан не верно.
`main` в названии быть не должно

2018-12-26 15:37 UTC, alinkov commented on src/main/java/com/Application.java
> +package main.java.com;
`app_interface` в названии пакета быть не должно

2018-12-26 15:37 UTC, alinkov commented on src/main/java/com/app_interface/MainInterface.java
> +                this.choose_law_mech();
обязательно нужно break добавлять 
иначе будет выполнено все то, что ниже

2018-12-26 16:12 UTC, rogozhinski commented on src/main/java/com/app_interface/MainInterface.java
> +                this.choose_law_mech();
Спасибо за отзыв! К концу каникул глубоко переработаю ДЗ.

2019-01-10 23:50 UTC, rogozhinski commented
## Изменения по сравнению с предыдущей попыткой №1

	1. Решена проблема сборки и запуска jar-файла: исправлен путь к source folder в настройках проекта в IDEA.

	2. Код зарефакторен с учетом комментариев Александра Линькова и Кирилла Васильева к пулл-реквесту.

	3. Применение checkstyle-plugin показало 202 недочета (в основном - whitespace и javadoc и sizes). Наиболее грубые из них были исправлены.

	4. Наименование сущностей приведено к приемлемой для java форме (избавился от питоновского camel-style)

	4. Добавлены комментарии к классам и методам.

	5. Приведен в порядок pom-файл: убраны лишние зависимости, добавлены требуемые плагины.

	6. Были добавлены тесты: они находятся в общей сборке приложения.

2019-01-11 06:31 UTC, alinkov commented
Папочку out удали и добавь ее в gitignore

2019-01-11 07:16 UTC, rogozhinski commented
> 
> 
> Папочку out удали и добавь ее в gitignore

Сделано

2019-01-11 08:04 UTC, alinkov requested changes

2019-01-11 08:04 UTC, alinkov commented on src/test/java/com/mechanics/TestInertiaLaw.java
> +        assertEquals(inertiaLaw.massCalc(force, acceleration), force/acceleration, 1e-6);
в assertEquals вначале идет ожидаемое значение, а потом что получилось в методе.
Так что надо бы поменять их местами

2019-01-11 08:04 UTC, alinkov commented on src/main/java/com/appInterface/MyUtils.java
> +            double newValue = MyUtils.enterDouble(title);
а зачем тут newValue, если будет возвращен 0?

2019-01-11 08:04 UTC, alinkov commented on src/main/java/com/appInterface/MyUtils.java
> +package com.appInterface;
пакеты так не именуются
com.app.interface

2019-01-11 08:04 UTC, alinkov commented on src/main/java/com/appInterface/MainInterface.java
> +public class MainInterface {
не очень хорошо в названии иметь Interface...

2019-01-11 08:04 UTC, alinkov commented on src/main/java/com/appInterface/MainInterface.java
> +                InertiaLawInterface inertiaInstance = new InertiaLawInterface();
вот тут очень хорошо подошел бы паттерн стратегия

2019-01-11 08:04 UTC, alinkov commented on src/main/java/com/electrodynamics/Capacitor.java
> +package com.electrodynamics;
как-то не очень хорошо по пакетам разложено.
Уж очень далеко получается CapacitorInterface от Capacitor.

2019-01-11 08:04 UTC, alinkov commented on src/main/java/com/electrodynamics/OhmLaw.java
> +        return voltage / resistance;
проверку resistance на 0 бы еще

2019-01-11 08:04 UTC, alinkov commented on pom.xml
> +        <dependency>
org.apache.maven.plugin-tools и com.fasterxml.jackson.core не нужны

2019-01-11 15:37 UTC, alinkov commented
Т.к. срок истекает, задачу засчитываю с недочетами

2019-01-11 15:37 UTC, closed without merging